# command : `$ docker-compose up -d`
version: '3.2'

services:
    db:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=matches
            - POSTGRES_USER=matches-user
            - POSTGRES_PASSWORD=matches-password
        ports:
            - "5432:5432"

volumes:
    db-data: {}
